version: "3.7"
services:
    rdbms:
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_AGENT_ENABLED=1
        entrypoint: /srv/rdbms/entrypoint.sh
        image: mcr.microsoft.com/mssql/server:2019-CU4-ubuntu-16.04
        # TODO: `published` is nodig vanwege [beperkingen Docker for Desktop onder macOS](https://docs.docker.com/docker-for-mac/networking/#known-limitations-use-cases-and-workarounds/)
        # Processen op de Docker host kunnen nog wel luisteren op bijv. TCP localhost:1433. In dat geval wordt de container onbereikbaar op dat adres.
        # Luisteren er géén processen op de Docker host op TCP localhost:1433, dan bereik je ineens deze Docker container op dat adres.
        ports:
            - target: "1433"
              published: "1433"
              protocol: tcp
              mode: bridge
        # TODO: nodig voor installatie van VS Code MS SQL Server extension (infosec)
        user: root
        networks:
            - webapplicatie
        volumes:
            - ./:/srv/rdbms:cached
            - type: volume
              source: home_mssql
              target: /home/mssql/
              volume:
                  nocopy: true
        secrets:
            - source: password_rdbms_superuser
              uid: "0"
              gid: "0"
              mode: "0440"
secrets:
    password_rdbms_superuser:
        file: ../password_rdbms_superuser.txt
volumes:
    home_mssql:
networks:
    webapplicatie:
        name: webapplicatie
